group=org.leavesmc.leaves
version=26.1.2-R0.1-SNAPSHOT
mcVersion=26.1.2
paperRef=70eaed653d2260e42e510ea16e8fcb50152aa5ef
channel=STABLE
preVersion=true
paper.runDisableWatchdog=true

# This is the current API version for use in (paper-/leaves-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.1.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
