group=org.leavesmc.leaves
version=26.2-R0.1-SNAPSHOT
mcVersion=26.2
paperRef=58e1f844b1f37a2efe4e9536f57f4a288733e0cb
channel=STABLE
preVersion=true
paper.runDisableWatchdog=true

# This is the current API version for use in (paper-/leaves-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.2

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
