group=org.leavesmc.leaves
version=26.3-R0.1-SNAPSHOT
mcVersion=26.3
paperRef=0fd1cf72ffb8eefe8bd4899620695a77659db42b
channel=ALPHA
preVersion=true
paper.runDisableWatchdog=true

# This is the current API version for use in (paper-/leaves-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.3

org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
